package com.muthohhari.myrecyclerview;

import com.muthohhari.myrecyclerview.model.President;

import java.util.ArrayList;

public class DataPresident {
    private static String[][] data = new String[][]{
            {"Soekarno", "Presiden Pertama RI", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Presiden_Sukarno.jpg/418px-Presiden_Sukarno.jpg", "Soekarno dilahirkan dengan seorang ayah yang bernama Raden Soekemi Sosrodihardjo dan ibunya yaitu Ida Ayu Nyoman Rai. Keduanya bertemu ketika Raden Soekemi yang merupakan seorang guru ditempatkan di Sekolah Dasar Pribumi di Singaraja, Bali. Nyoman Rai merupakan keturunan bangsawan dari Bali dan beragama Hindu, sedangkan Raden Soekemi sendiri beragama Islam. Mereka telah memiliki seorang putri yang bernama Sukarmini sebelum Soekarno lahir. Ketika kecil Soekarno tinggal bersama kakeknya, Raden Hardjokromo di Tulung Agung, Jawa Timur."},
            {"Soeharto", "Presiden Kedua RI", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/President_Suharto%2C_1993.jpg/468px-President_Suharto%2C_1993.jpg", "Soeharto tidak seperti anak desa lainnya yang harus bekerja di sawah. Dalam usia yang sangat muda, ia disekolahkan oleh Kertosudiro. Tidak ada berita-berita mengenai masa Soeharto di Sekolah Rakyat (setingkat SD). Kesan Soeharto pada masa SD itu hanya pada ingatannya tentang kerbau-kerbaunya. Dunia Soeharto hanya berkutat pada penggembalaan kerbau, jauh dari cerita-cerita anak yang didapat dari buku-buku yang kerap dibaca anak-anak SD. Hal ini berbeda misalnya dengan cerita Soekarno sewaktu dia masih di SD yang banyak berkisah tentang masa sekolahnya dan apa yang dibacanya, begitu juga dengan Hatta dan Sjahrir yang sejak kecil sudah akrab dengan Karl May atau cerita dari novel-novel Charles Dickens."},
            {"Bacharuddin Jusuf Habibie", "Presiden Ketiga RI", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Bacharuddin_Jusuf_Habibie_official_portrait.jpg/520px-Bacharuddin_Jusuf_Habibie_official_portrait.jpg", "Prof. Dr. Ing. H. Bacharuddin Jusuf Habibie, FREng (lahir di Parepare, Sulawesi Selatan, 25 Juni 1936; umur 82 tahun) adalah Presiden Republik Indonesia yang ketiga. Ia menggantikan Soeharto yang mengundurkan diri dari jabatan presiden pada tanggal 21 Mei 1998. Jabatannya digantikan oleh Abdurrahman Wahid (Gus Dur) yang terpilih sebagai presiden pada 20 Oktober 1999 oleh MPR hasil Pemilu 1999. Dengan menjabat selama 2 bulan dan 7 hari sebagai wakil presiden, dan 1 tahun dan 5 bulan sebagai presiden, Habibie merupakan Wakil Presiden dan juga Presiden Indonesia dengan masa jabatan terpendek. Saat ini namanya diabadikan sebagai nama salah satu universitas di Gorontalo, menggantikan nama Universitas Negeri Gorontalo."},
            {"Abdurrahman Wahid", "Presiden Keempat RI", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/President_Abdurrahman_Wahid_-_Indonesia.jpg/486px-President_Abdurrahman_Wahid_-_Indonesia.jpg", "Dr.(H.C.) K. H. Abdurrahman Wahid atau yang akrab disapa Gus Dur (lahir di Jombang, Jawa Timur, 7 September 1940 – meninggal di Jakarta, 30 Desember 2009 pada umur 69 tahun)[1] adalah tokoh Muslim Indonesia dan pemimpin politik yang menjadi Presiden Indonesia yang keempat dari tahun 1999 hingga 2001. Ia menggantikan Presiden B.J. Habibie setelah dipilih oleh Majelis Permusyawaratan Rakyat hasil Pemilu 1999. Penyelenggaraan pemerintahannya dibantu oleh Kabinet Persatuan Nasional. Masa kepresidenan Abdurrahman Wahid dimulai pada 20 Oktober 1999 dan berakhir pada Sidang Istimewa MPR pada tahun 2001. Tepat 23 Juli 2001, kepemimpinannya digantikan oleh Megawati Soekarnoputri setelah mandatnya dicabut oleh MPR. Abdurrahman Wahid adalah mantan ketua Tanfidziyah (badan eksekutif) Nahdlatul Ulama dan pendiri Partai Kebangkitan Bangsa (PKB)."},
            {"Megawati Soekarnoputri", "Presiden Kelima RI", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/President_Megawati_Sukarnoputri_-_Indonesia.jpg/540px-President_Megawati_Sukarnoputri_-_Indonesia.jpg", " Hj. Dyah Permata Megawati Setyawati Soekarnoputri atau umumnya lebih dikenal sebagai Megawati Soekarnoputri atau biasa disapa dengan panggilan \"Mbak Mega\" (lahir di Yogyakarta, 23 Januari 1947; umur 72 tahun) adalah Presiden Indonesia yang kelima yang menjabat sejak 23 Juli 2001 sampai 20 Oktober 2004. Ia merupakan presiden wanita Indonesia pertama dan puteri dari presiden Indonesia pertama, Soekarno, yang kemudian mengikuti jejak ayahnya menjadi Presiden Indonesia. Pada 20 September 2004, ia kalah suara dari Susilo Bambang Yudhoyono dalam Pemilu Presiden 2004 putaran yang kedua.\n" +
                    "\n" +
                    "Ia menjadi presiden setelah MPR mengadakan Sidang Istimewa MPR pada tahun 2001. Sidang Istimewa MPR ini diadakan dalam menanggapi langkah Presiden Abdurrahman Wahid (Gus Dur) yang membekukan lembaga MPR/DPR dan Partai Golkar. Ia dilantik pada 23 Juli 2001. Sebelumnya dari tahun 1999–2001, ia menjabat Wakil Presiden pada pemerintahan Presiden Abdurrahman Wahid (Gus Dur).\n" +
                    "\n" +
                    "Megawati juga merupakan ketua umum Partai Demokrasi Indonesia Perjuangan (PDI-P) sejak memisahkan diri dari Partai Demokrasi Indonesia pada tahun 1999."},
            {"Susilo Bambang Yudhoyono", "Presiden Keenam RI", "https://upload.wikimedia.org/wikipedia/commons/5/58/Presiden_Susilo_Bambang_Yudhoyono.png", "Jenderal (HOR.) TNI (Purn.) Prof. Dr. H. Susilo Bambang Yudhoyono, M.A., GCB., AC.(lahir di Tremas, Arjosari, Pacitan, Jawa Timur, Indonesia, 9 September 1949; umur 69 tahun) adalah Presiden Indonesia ke-6 yang menjabat sejak 20 Oktober 2004 hingga 20 Oktober 2014.Ia adalah Presiden pertama di Indonesia yang dipilih melalui jalur pemilu. Ia, bersama Wakil Presiden Muhammad Jusuf Kalla, terpilih dalam Pemilu Presiden 2004.[1][2] Ia berhasil melanjutkan pemerintahannya untuk periode kedua dengan kembali memenangkan Pemilu Presiden 2009, kali ini bersama Wakil Presiden Boediono. Sejak era reformasi dimulai, Susilo Bambang Yudhoyono merupakan Presiden Indonesia pertama yang menyelesaikan masa kepresidenan selama 5 tahun dan berhasil terpilih kembali untuk periode kedua."},
            {"Joko Widodo", "Presiden Ketujuh RI", "https://upload.wikimedia.org/wikipedia/commons/1/1c/Joko_Widodo_2014_official_portrait.jpg", "Ir. H. Joko Widodo atau Jokowi (lahir di Surakarta, Jawa Tengah, 21 Juni 1961; umur 57 tahun) adalah Presiden ke-7 Indonesia yang mulai menjabat sejak 20 Oktober 2014. Ia terpilih bersama Wakil Presiden Muhammad Jusuf Kalla dalam Pemilu Presiden 2014. Jokowi pernah menjabat Gubernur DKI Jakarta sejak 15 Oktober 2012 hingga 16 Oktober 2014 didampingi Basuki Tjahaja Purnama sebagai wakil gubernur. Sebelumnya, ia adalah Wali Kota Surakarta (Solo), sejak 28 Juli 2005 hingga 1 Oktober 2012 didampingi F.X. Hadi Rudyatmo sebagai wakil wali kota. Dua tahun menjalani periode keduanya menjadi Wali Kota Solo, Jokowi ditunjuk oleh partainya, Partai Demokrasi Indonesia Perjuangan (PDI-P), untuk bertarung dalam pemilihan Gubernur DKI Jakarta berpasangan dengan Basuki Tjahaja Purnama (Ahok)."}
    };

    public static ArrayList<President> getListData() {
        President president = null;
        ArrayList<President> list = new ArrayList<>();
        for (String[] aData : data) {
            president = new President();
            president.setName(aData[0]);
            president.setRemarks(aData[1]);
            president.setPhoto(aData[2]);
            president.setDescription(aData[3]);

            list.add(president);
        }

        return list;
    }
}
